spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tenpo_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}
    timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  cache:
    type: redis

retry:
  maxAttempts: 3
  delay: 2000
rate-limit:
  requests: 3
  time-window-seconds: 60

external:
  api:
    wiremockUrl: http://localhost:8081/external-percentage
    wiremockAdminUrl: http://localhost:8081/__admin
